#!/bin/bash


#Check for config files
CONF=$(ls -A /config)
www=$(ls -A /html)


if [ "$CONF" =  "" ];then

	tar -xzvf /opt/config.tgz -C /config/

fi

#www
if [ "$www" =  "" ];then

	cp -rfv /opt/index.html /html/

fi


chown -R www-data.www-data /config
chown -R www-data.www-data /html


#Main Job
exec /usr/sbin/apache2ctl -DFOREGROUND
